complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    ignorePrivate: true

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  ReturnCount:
    active: false
