name: CI
on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all checks
        run: ./gradlew --no-daemon clean check
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create credentials file
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $CREDENTIALS -> credentials
      - name: Deploy to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials
        run: ./gradlew --no-daemon app:assembleDebug app:appDistributionUploadDebug -PappVersionNameSuffix=.$GITHUB_RUN_NUMBER
      - name: Delete credentials file
        run: rm credentials
